CREATE TYPE "EVENT_STATUS" AS ENUM ('DRAFT', 'PUBLISHED', 'CANCELLED');

UPDATE "Event"
SET "status" = CASE UPPER(COALESCE(NULLIF("status", ''), 'DRAFT'))
  WHEN 'PUBLISHED' THEN 'PUBLISHED'
  WHEN 'CANCELLED' THEN 'CANCELLED'
  ELSE 'DRAFT'
END;

ALTER TABLE "Event"
ALTER COLUMN "status" DROP DEFAULT,
ALTER COLUMN "status" TYPE "EVENT_STATUS" USING ("status"::"EVENT_STATUS"),
ALTER COLUMN "status" SET DEFAULT 'DRAFT';
